language: rust
sudo: false

rust:
  - stable
  - beta
  - nightly

addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev

before_script:
- |
    pip install 'travis-cargo<0.2' --user &&
    export PATH=$HOME/.local/bin:$PATH

script:
- |
    (cd serde && travis-cargo build) &&
    (cd serde && travis-cargo test) &&
    (cd serde_tests && travis-cargo test) &&
    (cd serde_macros && travis-cargo --only nightly test) &&
    (cd serde_macros && travis-cargo --only nightly bench) &&
    (cd serde && travis-cargo --only stable doc) &&
    (cd serde_codegen && travis-cargo --only stable doc)

after_success:
- (cd serde && travis-cargo --only stable doc-upload)
- (cd serde_tests && travis-cargo coveralls --no-sudo)

env:
  global:
    # override the default `--features unstable` used for the nightly branch (optional)
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""

    # encrypted github token for doc upload (see `GH_TOKEN` link above)
    - secure: HO41LMpMXkF2In9+1sxWVu7fgolL+y9+4Q5PI6wZX2L5pDwpPJCjxaQarQXCEnoIxED1PlP03JuF7ULNz0zw1ylYhAOfOSdkxFZRnE2wMZqq6qvXBHwyMiDrAociIzoPKSGv7JVrKPsjsnd+96K6xxueIodQZrmAdyq7N/M82Mc=
